routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'auth','as'=>'auth.', 'middleware' => ['auth']], function () {
    //Route index admin
    Route::get('/admin/index', 'QuestionController@index')->name('admin.index');

    //Questions Route
    Route::resource('questions', 'QuestionController');

    //Reponses Routes
    Route::get('/questions/addReponse/{id}', 'ReponseController@addReponse')->name('questions.addReponse');
    Route::post('/reponses/updated', 'ReponseController@update')->name('reponses.updated');
    Route::resource('reponses', 'ReponseController');

    //Route QCM User
    Route::get('/qcm/index', 'FrontendController@index')->name('qcm.index');
    Route::post('/qcm/calcule', 'FrontendController@calcul')->name('qcm.calcul');
});

resources/views/backend/reponses/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('errors'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('errors') }}
                            </div>
                        @endif
                        @include('layouts.navbar')
                        <form method="POST" @if(!@$show) action="{{ route('auth.reponses.store') }}" @endif>
                            @csrf
                            <input type="hidden" name="id_question" value="{{ @$id }}">
                            <div class="row p-3 copy" id="copy">
                                <div class="col-2">
                                    <span>Reponse</span>
                                </div>
                                <div class="col5">
                                    <input type="text" class="form-control" name="reponse[]" value="{{@$model->reponse}}">
                                </div>
                                <div class="col-3">
                                    <select class="form-control" aria-label="Résultat" name="resultat[]">
                                        <option value="true">Vrai</option>
                                        <option value="false">Faux</option>
                                    </select>
                                </div>
                                <div class="col-2 pt-1">
                                    <button type="button" class="btn btn-sm btn-primary add" id="addLigne"><i class="fas fa-plus"></i></button>
                                    <button type="button" class="btn btn-sm btn-danger remove" id="remove"><i class="fas fa-trash"></i></button>
                                </div>
                            </div>
                            <div id="copied">

                            </div>
                            <div class="form-group row">
                                <div class="col-sm-10 offset-2">
                                    <input type="hidden" name="id" value="{{@$model->id}}">
                                    <a type="button" href="{{route('auth.admin.index')}}"
                                       class="btn btn-light">Retour</a>
                                    @if(!@$show)
                                        <button type="submit"
                                                class="btn btn-primary waves-effect waves-light">{{(@$model)? 'Mise à jours' : 'Ajouter' }}</button>
                                    @endif
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/reponses/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('errors'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('errors') }}
                            </div>
                        @endif
                        @include('layouts.navbar')
                        <form method="POST" @if(!@$show) action="{{ route('auth.reponses.updated') }}" @endif>
                            @csrf
                            <input type="hidden" name="id_question" value="{{ @$id }}">
                            <div class="row p-3 copy" id="copy">
                                <div class="col-2">
                                    <span>Reponse</span>
                                </div>
                                <div class="col5">
                                    <input type="text" class="form-control" name="reponse" value="{{@$model->reponse}}" {{(@$show)?'disabled':''}}>
                                </div>
                                <div class="col-3">
                                    <select class="form-control" aria-label="Résultat" name="resultat" {{(@$show)?'disabled':''}}>
                                        <option value="true" {{($model->resultat)? 'selected': ''}}>Vrai</option>
                                        <option value="false" {{(!$model->resultat)? 'selected': ''}}>Faux</option>
                                    </select>
                                </div>
                            </div>
                            <div id="copied">

                            </div>
                            <div class="form-group row">
                                <div class="col-sm-10 offset-2">
                                    <input type="hidden" name="id" value="{{@$model->id}}">
                                    <a type="button" href="{{route('auth.reponses.index')}}"
                                       class="btn btn-light">Retour</a>
                                    @if(!@$show)
                                        <button type="submit" class="btn btn-primary waves-effect waves-light">{{(@$model)? 'Mise à jours' : 'Ajouter' }}</button>
                                    @endif
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/reponses/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('message'))
                            <div class="alert alert-success" role="alert">
                                {{ session('message') }}
                            </div>
                        @endif
                        @include('layouts.navbar')
                        <div class="row p-3">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Réponse</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @php $compteur = 1 @endphp
                                @foreach($all as $reponse)
                                    <tr>
                                        <th scope="row">{{ $compteur }}</th>
                                        <td>{{ $reponse->reponse }}</td>
                                        <td>
                                            <a href="{{ route('auth.reponses.show', [$reponse->id]) }}" class="btn btn-sm btn-secondary">Afficher</a>
                                            <a href="{{ route('auth.reponses.edit', [$reponse->id])}}" class="btn btn-sm btn-primary">Modifier</a>
                                            <form action="{{ route('auth.reponses.destroy', [$reponse->id]) }}" method="POST">
                                                <input type="hidden" name="_token" id="csrf-token" value="{{ \Illuminate\Support\Facades\Session::token() }}" />
                                                <input type="hidden" name="_method" value="delete" />
                                                <button type="submit" onclick="return myFunction();" class="btn btn-sm btn-danger mt-2">Supprimer</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @php $compteur++ @endphp
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection