routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'auth','as'=>'auth.', 'middleware' => ['auth']], function () {
    //Route index admin
    Route::get('/admin/index', 'QuestionController@index')->name('admin.index');

    //Questions Route
    Route::resource('questions', 'QuestionController');

    //Reponses Routes
    Route::get('/questions/addReponse/{id}', 'ReponseController@addReponse')->name('questions.addReponse');
    Route::post('/reponses/updated', 'ReponseController@update')->name('reponses.updated');
    Route::resource('reponses', 'ReponseController');

    //Route QCM User
    Route::get('/qcm/index', 'FrontendController@index')->name('qcm.index');
    Route::post('/qcm/calcule', 'FrontendController@calcul')->name('qcm.calcul');
});

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use App\Reponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FrontendController extends Controller
{
    public function index(){
        $all = Question::with('reponses')->orderBy('id', 'asc')->get();
        return view('frontend.listQuestion', [
            'all' => $all
        ]);
    }

    public function calcul(Request $request){
        $iteration = 1;
        $increment = 0;
        foreach ($request->reponses as $reponse){
            $score[0] = 0;
            $res = explode(".", $reponse);
            $reponses = DB::table('questions_reponses')->where('question_id', $res[1])->get();
            $id_reponses_exact = [];
            foreach ($reponses as $rep){
                array_push($id_reponses_exact, $rep->reponse_id);
            }
            $question = Question::find($res[1]);
            if($question->type=="reponse"){
                $resultat = Reponse::find($res[0]);
                if($resultat->resultat === 1){
                    $increment = $increment+1;
                    array_push($score, $question->score);
                }
            }else{
                $rep = Reponse::whereIn('id', $id_reponses_exact)->get();
                $count = 0;
                foreach ($rep as $element){
                    if($element->resultat == 1)
                        $count++;
                }
                $part = $question->score / $count;

                $resultat = Reponse::find($res[0]);
                if($resultat->resultat == 1){
                    $increment = $increment+1;
                    array_push($score, $part);
                }
            }
            $iteration++;
        }
        $total = array_sum($score);
        return back()->with('score', $total);
    }
}

resources/views/frontend/listQuestion.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('score'))
                            <div class="alert alert-success" role="alert">
                                votre score est: {{ session('score') }}
                            </div>
                        @endif
                        <form method="post" action="{{ route('auth.qcm.calcul') }}">
                            @csrf
                            @foreach($all as $question)
                                <div class="card mb-3" style="width: 100%;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ $question->question }}</h5>
                                        @if(count($question->reponses) > 0)
                                            @if($question->type == "multi")
                                                @foreach($question->reponses as $reponse)
                                                    <div class="input-group-text mb-2">
                                                        <input type="checkbox" name="reponses[]" value="{{ $reponse->id }}.{{ $question->id }}"> <span class="ml-2">{{ $reponse->reponse }}</span>
                                                    </div>
                                                @endforeach
                                            @else
                                                @foreach($question->reponses as $reponse)
                                                    <div class="input-group-text mb-2">
                                                        <input type="radio" name="reponses[]" value="{{ $reponse->id }}.{{ $question->id }}"> <span class="ml-2">{{ $reponse->reponse }}</span>
                                                    </div>
                                                @endforeach
                                            @endif
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                            <button type="submit" class="btn btn-primary float-right">Valider</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection