routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'auth','as'=>'auth.', 'middleware' => ['auth']], function () {
    //Route index admin
    Route::get('/admin/index', 'QuestionController@index')->name('admin.index');

    //Questions Route
    Route::resource('questions', 'QuestionController');

    //Reponses Routes
    Route::get('/questions/addReponse/{id}', 'ReponseController@addReponse')->name('questions.addReponse');
    Route::post('/reponses/updated', 'ReponseController@update')->name('reponses.updated');
    Route::resource('reponses', 'ReponseController');

    //Route QCM User
    Route::get('/qcm/index', 'FrontendController@index')->name('qcm.index');
    Route::post('/qcm/calcule', 'FrontendController@calcul')->name('qcm.calcul');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function reponses()
    {
        return $this->belongsToMany('App\Reponse', 'questions_reponses');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class QuestionController extends Controller
{
    public function index(){
        $all = Question::all();
        return view('backend.admin.index',[
            "all" => $all
        ]);
    }
    public function create(){
        return view('backend.questions.create');
    }

    public function store(Request $request){
        $request->validate([
            'question' => 'required|min:4'
        ]);

        try {
            $modif = true;
            $model = Question::find($request->id);
            if (!$model) {
                $modif = false;
                $model = new Question();
            }
            $model->question = $request->question;
            $model->score = $request->score;
            $model->type = $request->type;
            $model->save();

        } catch (\Exception $e) {
            return redirect()->back()->with('errors', 'Erreur');
        }

        if($modif)
            return redirect()->route('auth.admin.index')->with('message', 'updated');
        else
            return redirect()->route('auth.admin.index')->with('message', 'created');
    }

    public function show($id){
        $show=true;
        $model=Question::with('reponses')->where('id',$id)->first();
        return view('backend.questions.create', [
            'show' => $show,
            'model'=> $model
        ]);
    }

    public function edit($id)
    {
        $model=Question::find($id);
        return view('backend.questions.create', [
            'model'=> $model
        ]);
    }

    public function destroy($id)
    {
        $model = Question::find($id);
        DB::table('questions_reponses')->where('question_id',$id)->delete();
        $model->delete();

        return back()->with('message', 'deleted');
    }
}

resources/views/backend/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('errors'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('errors') }}
                            </div>
                        @endif
                        @include('layouts.navbar')
                                <form method="POST" @if(!@$show) action="{{ route('auth.questions.store') }}" @endif>
                                    @csrf
                                    <div class="form-group mt-5">
                                        <label for="exampleFormControlTextarea1">Question:</label>
                                        <textarea class="form-control" id="exampleFormControlTextarea1" name="question" rows="3" {{(@$show)?'disabled':''}}>{{@$model->question}}</textarea>
                                    </div>
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group row">
                                                <label for="staticEmail" class="col-sm-2 col-form-label">Score:</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" name="score" id="staticEmail" value="{{@$model->score}}" {{(@$show)?'disabled':''}}>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="form-group row">
                                                <label for="staticEmail1" class="col-sm-2 col-form-label">Type:</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control" aria-label="Résultat" name="type" {{(@$show)?'disabled':''}}>
                                                        <option value="reponse" {{(@$model->type == 'reponse')? 'selected': ''}}>Une seule réponse</option>
                                                        <option value="multi" {{(@$model->type == 'multi')? 'selected': ''}}>Multi réponse</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-10 offset-2">
                                            <input type="hidden" name="id" value="{{@$model->id}}">
                                            <a type="button" href="{{route('auth.admin.index')}}"
                                               class="btn btn-light">Retour</a>
                                            @if(!@$show)
                                                <button type="submit"
                                                        class="btn btn-primary waves-effect waves-light">{{(@$model)? 'Mise à jours' : 'Ajouter' }}</button>
                                            @endif
                                        </div>
                                    </div>
                                </form>
                        @if(@$model)
                            @if(count($model->reponses) > 0)
                                @php $compteur = 1 @endphp
                                    <table class="table">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Reponse</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($model->reponses as $reponse)
                                            <tr>
                                                <th scope="row">{{ $compteur }}</th>
                                                <td>{{ $reponse->reponse }}</td>
                                                @if($reponse->resultat == 1)
                                                    <td>{{ 'Vrai' }}</td>
                                                @else
                                                    <td>{{ 'Faux' }}</td>
                                                @endif
                                            </tr>
                                        @php $compteur++ @endphp
                                        @endforeach
                                        </tbody>
                                    </table>
                            @endif
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection